/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: da268fb7f3e5cf33e8cc5a32e8c54e65)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SecuredChatAgent";
  }
  interface Env {
    AUTH_DB: D1Database;
    BETTER_AUTH_URL: "http://localhost:5173";
    BETTER_AUTH_SECRET: string;
    SecuredChatAgent: DurableObjectNamespace<
      import("./src/server").SecuredChatAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET">
  > {}
}
